name: "[Build] - Release Pipeline"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    get_version:
      name: "1. Get Version"
      runs-on: ubuntu-latest
      outputs:
        version: ${{ steps.get-version.outputs.version }}
      steps:
        - uses: actions/checkout@v4
        - name: get-pom-version
          uses: PERES-Richard/maven-get-version-action@v3.0.0
          id: get-version
    create_github_release:
      name: "2. Create Github Release"
      runs-on: ubuntu-latest
      needs: get_version
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            server-id: github
            settings-path: ${{ github.workspace }}
        - name: Build project
          run: |
            mvn -B package --file pom.xml
        - uses: softprops/action-gh-release@v2
          with:
            name: Release v${{ needs.get_version.outputs.version }}
            tag_name: v${{ needs.get_version.outputs.version }}
            target_commitish: ${{ github.head_ref || github.ref }}
            generate_release_notes: true
            draft: false
            files: target/*.jar
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
